// AUTH/USER_LOGIN
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_COMPLETED = 'USER_LOGIN_COMPLETED';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET';

// AUTH/USER_REGISTER
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_COMPLETED = 'USER_REGISTER_COMPLETED';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';

// AUTH/USER_LOGOUT
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_COMPLETED = 'USER_LOGOUT_COMPLETED';
export const USER_LOGOUT_ERROR = 'USER_LOGOUT_ERROR';

// BOOKINGS/WALLET
export const FETCH_WALLET = 'FETCH_WALLET';
export const FETCH_WALLET_REQUEST = 'FETCH_WALLET_REQUEST';
export const FETCH_WALLET_COMPLETED = 'FETCH_WALLET_COMPLETED';
export const FETCH_WALLET_ERROR = 'FETCH_WALLET_ERROR';

// BOOKINGS/ACTIVE
export const FETCH_ACTIVE_BOOKINGS = 'FETCH_ACTIVE_BOOKINGS';
export const FETCH_ACTIVE_BOOKINGS_REQUEST = 'FETCH_ACTIVE_BOOKINGS_REQUEST';
export const FETCH_ACTIVE_BOOKINGS_COMPLETED = 'FETCH_ACTIVE_BOOKINGS_COMPLETED';
export const FETCH_ACTIVE_BOOKINGS_ERROR = 'FETCH_ACTIVE_BOOKINGS_ERROR';

// BOOKINGS/COMPLETED
export const FETCH_COMPLETED_BOOKINGS = 'FETCH_COMPLETED_BOOKINGS';
export const FETCH_COMPLETED_BOOKINGS_REQUEST = 'FETCH_COMPLETED_BOOKINGS_REQUEST';
export const FETCH_COMPLETED_BOOKINGS_COMPLETED = 'FETCH_COMPLETED_BOOKINGS_COMPLETED';
export const FETCH_COMPLETED_BOOKINGS_ERROR = 'FETCH_COMPLETED_BOOKINGS_ERROR';

// BOOKINGS/CREATE
export const CREATE_BOOKING = 'CREATE_BOOKING';
export const CREATE_BOOKING_REQUEST = 'CREATE_BOOKING_REQUEST';
export const CREATE_BOOKING_COMPLETED = 'CREATE_BOOKING_COMPLETED';
export const CREATE_BOOKING_ERROR = 'CREATE_BOOKING_ERROR';
